// Code generated by MockGen. DO NOT EDIT.
// Source: ./notifier.go

// Package mock_src is a generated GoMock package.
package mock_src

import (
	reflect "reflect"
	constants "refurbedchallenge/notifier/constants"

	gomock "github.com/golang/mock/gomock"
)

// MockINotifierClient is a mock of INotifierClient interface.
type MockINotifierClient struct {
	ctrl     *gomock.Controller
	recorder *MockINotifierClientMockRecorder
}

// MockINotifierClientMockRecorder is the mock recorder for MockINotifierClient.
type MockINotifierClientMockRecorder struct {
	mock *MockINotifierClient
}

// NewMockINotifierClient creates a new mock instance.
func NewMockINotifierClient(ctrl *gomock.Controller) *MockINotifierClient {
	mock := &MockINotifierClient{ctrl: ctrl}
	mock.recorder = &MockINotifierClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotifierClient) EXPECT() *MockINotifierClientMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockINotifierClient) Notify(message string) chan constants.NotificationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", message)
	ret0, _ := ret[0].(chan constants.NotificationError)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockINotifierClientMockRecorder) Notify(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockINotifierClient)(nil).Notify), message)
}
